const fs = require('fs');
const lines = fs.readFileSync('src/App.tsx', 'utf8').split('\n');

const before = lines.slice(0, 3868);
const after = lines.slice(3962);

const newBlock = [
"  const alerts=woData.filter(w=>woOverall(w)<100&&(isDelayed(w.target)||isUrgent(w.target))).length;",
"  const [sidebarCollapsed,setSidebarCollapsed]=useState(false);",
"",
"  const SIDEBAR_MENUS=[",
"    {group:'Monitoring',items:[",
"      {id:'dashboard',label:'Dashboard',icon:'ti-layout-dashboard'},",
"      {id:'summary',label:'Summary Progress',icon:'ti-table'},",
"      {id:'detail',label:'Detail Progress',icon:'ti-zoom-in'},",
"    ]},",
"    {group:'Produksi',items:[",
"      ...(canRaw?[{id:'raw',label:'Raw Schedule',icon:'ti-calendar-event'}]:[]),",
"      ...(canRencana?[{id:'rencana',label:'Rencana Harian',icon:'ti-clipboard-list'}]:[]),",
"      ...(canWO?[{id:'wo',label:'Manajemen WO',icon:'ti-file-text'}]:[]),",
"    ]},",
"    {group:'System',items:[",
"      ...(['admin'].includes(user?.divisi)?[",
"        {id:'pekerja',label:'Master Pekerja',icon:'ti-users'},",
"        {id:'tracking',label:'Tracking Pekerja',icon:'ti-chart-bar'},",
"        {id:'activity',label:'Activity Log',icon:'ti-activity'},",
"        {id:'kendala',label:'Kendala'+(kendalaLog.length>0?' ('+kendalaLog.length+')':''),icon:'ti-message-report'},",
"        {id:'maintenance',label:'Maintenance',icon:'ti-tool'},",
"        {id:'masteruser',label:'System',icon:'ti-settings'},",
"      ]:[]),",
"    ]},",
"  ];",
"",
"  const activeLabel=SIDEBAR_MENUS.flatMap(g=>g.items).find(i=>i.id===tab)?.label||'Dashboard';",
"",
"  const handleNavTooltip=(e,label,show)=>{",
"    if(!sidebarCollapsed)return;",
"    let tip=document.getElementById('erp-global-tooltip');",
"    if(!tip){tip=document.createElement('div');tip.id='erp-global-tooltip';tip.className='erp-tooltip';document.body.appendChild(tip);}",
"    if(show){",
"      const rect=e.currentTarget.getBoundingClientRect();",
"      tip.textContent=label;",
"      tip.style.display='block';",
"      tip.style.top=(rect.top+rect.height/2)+'px';",
"    } else {",
"      tip.style.display='none';",
"    }",
"  };",
"",
"  return(",
"    <div style={{minHeight:'100vh',background:'#f1f5f9'}}>",
"      <style>{GCss}</style>",
"      {isOp?(",
"        <div style={{display:'flex',flexDirection:'column',minHeight:'100vh'}}>",
"          <div style={{background:'#fff',borderBottom:'1px solid #e2e8f0',padding:'0 16px',height:52,display:'flex',alignItems:'center',justifyContent:'space-between',position:'sticky',top:0,zIndex:100}}>",
"            <div style={{display:'flex',alignItems:'center',gap:10}}>",
"              <div style={{width:28,height:28,background:'#1d4ed8',borderRadius:7,display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:800,fontSize:13}}>V</div>",
"              <span style={{fontWeight:700,fontSize:14,color:'#1e293b'}}>Vista Teknik</span>",
"            </div>",
"            <div style={{display:'flex',alignItems:'center',gap:8}}>",
"              <span style={{background:cfg.bg,color:cfg.color,border:`1px solid ${cfg.color}30`,borderRadius:20,padding:'3px 12px',fontSize:11,fontWeight:700}}>{cfg.icon} {cfg.label}</span>",
"              <button onClick={()=>{setUser(null);setPage('landing');localStorage.removeItem('vista_admin_session');}} style={{background:'#f8fafc',border:'1px solid #e2e8f0',color:'#64748b',borderRadius:8,padding:'5px 12px',cursor:'pointer',fontSize:12,fontWeight:600}}>Keluar</button>",
"            </div>",
"          </div>",
"          <div style={{flex:1,overflowY:'auto'}}>",
"            <OperatorView woData={woData} setWoData={setWoData} user={user} renhar={renhar} setRenhar={setRenhar} pekerja={pekerja} createKendala={createKendala}/>",
"          </div>",
"          <div style={{position:'sticky',bottom:0,background:'#fff',borderTop:'1px solid #e2e8f0',display:'flex',height:52,zIndex:100}}>",
"            <button style={{flex:1,border:'none',background:'none',cursor:'pointer',fontFamily:'inherit',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:2,color:cfg.color}}>",
"              <span style={{fontSize:18}}>📋</span>",
"              <span style={{fontSize:9,fontWeight:700,letterSpacing:.3}}>Tugas Saya</span>",
"            </button>",
"          </div>",
"        </div>",
"      ):(",
"        <div style={{display:'flex',minHeight:'100vh'}}>",
"          <div className={`erp-sidebar${sidebarCollapsed?' collapsed':''}`}>",
"            <div className='logo-area'>",
"              <div className='logo-box'>V</div>",
"              <div className='logo-text'>",
"                <div style={{fontWeight:800,fontSize:13,color:'#1e293b',lineHeight:1.2}}>Vista Teknik</div>",
"                <div style={{fontSize:9,color:'#94a3b8',marginTop:2,lineHeight:1.3}}>Electrical Switchboard Manufacturing</div>",
"              </div>",
"            </div>",
"            <div style={{flex:1,overflowY:'auto',overflowX:'hidden'}}>",
"              {SIDEBAR_MENUS.map(group=>(",
"                <div key={group.group}>",
"                  <div className='nav-group-label'>{group.group}</div>",
"                  {group.items.map(item=>(",
"                    <div key={item.id} className={`nav-item${tab===item.id?' active':''}`} onClick={()=>setTab(item.id)} onMouseEnter={(e)=>handleNavTooltip(e,item.label,true)} onMouseLeave={(e)=>handleNavTooltip(e,item.label,false)}>",
"                      <i className={`ti ${item.icon}`} aria-hidden='true'/>",
"                      <span className='nav-text'>{item.label}</span>",
"                    </div>",
"                  ))}",
"                </div>",
"              ))}",
"            </div>",
"            <div className='user-area'>",
"              <div style={{width:28,height:28,minWidth:28,borderRadius:'50%',background:'#eff6ff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:10,fontWeight:800,color:'#1d4ed8',flexShrink:0}}>",
"                {(user?.name||user?.nama||'A').slice(0,2).toUpperCase()}",
"              </div>",
"              <div className='user-info'>",
"                <div style={{fontWeight:700,fontSize:12,color:'#1e293b',overflow:'hidden',textOverflow:'ellipsis'}}>{user?.name||user?.nama}</div>",
"                <div style={{fontSize:10,color:'#94a3b8'}}>{cfg?.label||'Admin'}</div>",
"              </div>",
"              <button onClick={()=>{setUser(null);setPage('landing');localStorage.removeItem('vista_admin_session');}} style={{background:'none',border:'none',cursor:'pointer',color:'#94a3b8',fontSize:16,flexShrink:0,padding:2}} title='Keluar'>",
"                <i className='ti ti-logout' aria-hidden='true'/>",
"              </button>",
"            </div>",
"          </div>",
"          <div className='erp-main'>",
"            <div className='erp-topbar'>",
"              <button className='erp-toggle-btn' onClick={()=>setSidebarCollapsed(p=>!p)} title='Toggle sidebar'>",
"                <i className={`ti ${sidebarCollapsed?'ti-layout-sidebar-left-expand':'ti-layout-sidebar-left-collapse'}`} style={{fontSize:18}} aria-hidden='true'/>",
"              </button>",
"              <div style={{display:'flex',alignItems:'center',gap:6}}>",
"                <span style={{fontSize:13,fontWeight:700,color:'#1e293b'}}>{activeLabel}</span>",
"                <span style={{color:'#94a3b8',fontSize:12}}> / Vista Teknik</span>",
"              </div>",
"              <div style={{marginLeft:'auto',display:'flex',alignItems:'center',gap:10}}>",
"                {alerts>0&&(",
"                  <span style={{background:'#fef2f2',border:'1px solid #fecaca',color:'#dc2626',borderRadius:20,padding:'3px 12px',fontSize:11,fontWeight:700}}>🔔 {alerts} peringatan</span>",
"                )}",
"                <span style={{fontSize:12,color:'#475569',fontWeight:500}}>{user?.name||user?.nama}</span>",
"                <span style={{background:cfg.bg,color:cfg.color,border:`1px solid ${cfg.color}30`,borderRadius:20,padding:'3px 12px',fontSize:11,fontWeight:700}}>{cfg.icon} {cfg.label}</span>",
"              </div>",
"            </div>",
"            <div className='erp-content'>",
"              {tab==='dashboard'&&<Dashboard woData={woData}/>}",
"              {tab==='summary'&&<SummaryProgress woData={woData}/>}",
"              {tab==='detail'&&<DetailProgress woData={woData}/>}",
"              {tab==='raw'&&<RawSchedule woData={woData} rawData={rawData} setRawData={setRawData} renhar={renhar} setRenhar={setRenhar} pekerja={pekerja} createRaw={createRaw} updateRaw={updateRaw} removeRaw={removeRaw} refetchRaw={refetchRaw} createRenhar={createRenhar} updateRenhar={updateRenhar} removeRenhar={removeRenhar} logActivity={logActivity} user={user}/>}",
"              {tab==='rencana'&&<RencanaHarian rawData={rawData} woData={woData} renhar={renhar} setRenhar={setRenhar} pekerja={pekerja} createRenhar={createRenhar} updateRenhar={updateRenhar} removeRenhar={removeRenhar} logActivity={logActivity} user={user}/>}",
"              {tab==='wo'&&<ManajemenWO woData={woData} setWoData={setWoData} createWO={createWO} updateWO={updateWO} removeWO={removeWO} logActivity={logActivity} user={user}/>}",
"              {tab==='pekerja'&&<MasterPekerja pekerja={pekerja} setPekerja={setPekerja} createPekerja={createPekerja} updatePekerja={updatePekerja} removePekerja={removePekerja} logActivity={logActivity} user={user}/>}",
"              {tab==='tracking'&&<TrackingPekerja pekerja={pekerja} renhar={renhar}/>}",
"              {tab==='maintenance'&&<MaintenanceTab user={user} logActivity={logActivity}/>}",
"              {tab==='kendala'&&<KendalaInbox kendalaLog={kendalaLog} removeKendala={removeKendala}/>}",
"              {tab==='activity'&&<ActivityLogView activityLog={activityLog} user={user}/>}",
"              {tab==='masteruser'&&<SystemTab user={user} logActivity={logActivity} activityLog={activityLog} pekerja={pekerja} setPekerja={setPekerja} createPekerja={createPekerja} updatePekerja={updatePekerja} removePekerja={removePekerja}/>}",
"            </div>",
"          </div>",
"        </div>",
"      )}",
"    </div>",
"  );",
];

const result = [...before, ...newBlock, ...after];
fs.writeFileSync('src/App.tsx', result.join('\n'), 'utf8');
console.log('Total baris baru:', result.length);
console.log('✅ Layout berhasil!');
