-- ============================================================================================
-- PRODUKSI STOK (2 Okt 2026) - DRAFT. Jalankan di Supabase SQL Editor (tim apply skema manual).
-- Produksi komponen setengah jadi SENGAJA untuk stok, TERPISAH TOTAL dari WO/Raw Schedule:
-- tidak ada FK/join ke panels, raw_schedule, renhar, fcs_timer_kerja. Satu-satunya hubungan ke
-- sisi WO: MEMBACA aturan proses di bom_proses_relevan (aturan yang sama dgn Raw Schedule/Generate
-- Jadwal) saat batch dibuat, lewat komponen BOM acuan tiap item stok.
--
-- Aturan (disetujui user 2 Okt 2026):
--  - Tahap batch = proses relevan komponen BOM acuan yang termasuk POTONG/BENDING/STEL/FINISHING/
--    RENDAM/PAINTING (RAKIT/PASANG/WIRING/QC tidak), urutan produksi. DISALIN saat batch dibuat
--    (perubahan Master Data di tengah jalan gak merusak batch yang berjalan).
--  - qty_selesai = total diproses (TERMASUK reject); baik = selesai - reject. Tidak ada rework.
--  - Tersedia tahap pertama = target - unit hidup (baik tahap pertama - semua reject tahap
--    sesudahnya) -> reject di tahap mana pun diganti potongan BARU. Tahap lain = baik tahap
--    sebelumnya - selesai tahap ini. Tahap bisa jalan paralel.
--  - Selesai = baik tahap terakhir >= target DAN tidak ada WIP -> 1x transaksi 'masuk'
--    (otomatis_produksi) sejumlah baik tahap terakhir. Kurangi target: WIP tetap dituntaskan.
--  - Batal: status batal, baik tahap terakhir yang sudah ada (kalau > 0) tetap masuk stok, WIP
--    ditinggal.
--  - Increment qty ATOMIK di DB, baris batch dikunci (FOR UPDATE) per simpan - operator paralel
--    di tahap yang sama gak saling timpa. Semua validasi di server.
--  - Idempoten berlapis: status aktif->selesai/batal cuma sekali (baris dikunci), penanda
--    stok_transaksi_id, + UNIQUE index referensi transaksi otomatis_produksi.
-- Satu transaksi: gagal di langkah mana pun = batal semua.
-- ============================================================================================
BEGIN;

-- 1. Komponen BOM acuan per item stok --------------------------------------------------------
ALTER TABLE public.komponen_stok
  ADD COLUMN IF NOT EXISTS bom_tipe_panel    text,
  ADD COLUMN IF NOT EXISTS bom_kode_komponen text;
COMMENT ON COLUMN public.komponen_stok.bom_kode_komponen IS 'Komponen BOM acuan (bom_master.kode_komponen, bersama bom_tipe_panel). Tahap Produksi Stok dibaca dari bom_proses_relevan acuan ini - satu aturan dgn WO.';
-- Backfill (keputusan user: acuan tipe FS): UNP->FS.10 UNP, HGR->FS.19 Hanger, FR-*->FS.1 Frame.
UPDATE public.komponen_stok SET bom_tipe_panel = 'FS',
  bom_kode_komponen = CASE WHEN jenis = 'UNP' THEN 'FS.10' WHEN jenis = 'HGR' THEN 'FS.19' WHEN jenis LIKE 'FR-%' THEN 'FS.1' END
WHERE bom_kode_komponen IS NULL AND (jenis IN ('UNP','HGR') OR jenis LIKE 'FR-%');

-- 2. Tabel -----------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.produksi_stok_batch (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  komponen_id        bigint  NOT NULL REFERENCES public.komponen_stok(id) ON DELETE RESTRICT,
  target_qty         integer NOT NULL CHECK (target_qty > 0),
  status             text    NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','selesai','batal')),
  bom_tipe_panel     text    NOT NULL,   -- snapshot acuan saat batch dibuat
  bom_kode_komponen  text    NOT NULL,
  stok_transaksi_id  bigint  REFERENCES public.komponen_stok_transaksi(id) ON DELETE SET NULL,
  created_by         text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  selesai_at         timestamptz,
  dibatalkan_oleh    text,
  alasan_batal       text
);
CREATE INDEX IF NOT EXISTS produksi_stok_batch_status_idx ON public.produksi_stok_batch (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.produksi_stok_tahap (
  batch_id     bigint   NOT NULL REFERENCES public.produksi_stok_batch(id) ON DELETE CASCADE,
  tahap        text     NOT NULL CHECK (tahap IN ('POTONG','BENDING','STEL','FINISHING','RENDAM','PAINTING')),
  urutan       smallint NOT NULL,
  qty_selesai  integer  NOT NULL DEFAULT 0 CHECK (qty_selesai >= 0),
  qty_reject   integer  NOT NULL DEFAULT 0 CHECK (qty_reject >= 0 AND qty_reject <= qty_selesai),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (batch_id, tahap),
  UNIQUE (batch_id, urutan)
);

CREATE TABLE IF NOT EXISTS public.produksi_stok_log (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id             bigint  NOT NULL REFERENCES public.produksi_stok_batch(id) ON DELETE CASCADE,
  tahap                text    NOT NULL,
  qty_sesi_ini         integer NOT NULL CHECK (qty_sesi_ini > 0),
  qty_reject_sesi_ini  integer NOT NULL DEFAULT 0 CHECK (qty_reject_sesi_ini >= 0 AND qty_reject_sesi_ini <= qty_sesi_ini),
  foto_urls            text[]  NOT NULL CHECK (cardinality(foto_urls) >= 1),
  operator_id          bigint,
  operator_nama        text,
  catatan              text,
  mulai_at             timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS produksi_stok_log_batch_idx ON public.produksi_stok_log (batch_id, created_at DESC);

-- Idempotensi lapis DB: 1 batch = maks 1 transaksi stok otomatis.
CREATE UNIQUE INDEX IF NOT EXISTS komponen_stok_transaksi_produksi_unik
  ON public.komponen_stok_transaksi (referensi) WHERE sumber = 'otomatis_produksi';

-- RLS: pola tabel app lain (otentikasi di level app).
ALTER TABLE public.produksi_stok_batch ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produksi_stok_tahap ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produksi_stok_log   ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produksi_stok_batch_anon_all ON public.produksi_stok_batch;
DROP POLICY IF EXISTS produksi_stok_tahap_anon_all ON public.produksi_stok_tahap;
DROP POLICY IF EXISTS produksi_stok_log_anon_all   ON public.produksi_stok_log;
CREATE POLICY produksi_stok_batch_anon_all ON public.produksi_stok_batch FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY produksi_stok_tahap_anon_all ON public.produksi_stok_tahap FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY produksi_stok_log_anon_all   ON public.produksi_stok_log   FOR ALL USING (true) WITH CHECK (true);

-- 3. Tahap berlaku dari aturan WO (bom_proses_relevan) ------------------------------------------
CREATE OR REPLACE FUNCTION public.produksi_stok_tahap_berlaku(p_tipe_panel text, p_kode_komponen text)
RETURNS TABLE (tahap text, urutan smallint) LANGUAGE sql STABLE AS $$
  SELECT r.jenis_pekerjaan, (row_number() OVER (ORDER BY array_position(
           ARRAY['POTONG','BENDING','STEL','FINISHING','RENDAM','PAINTING'], r.jenis_pekerjaan)))::smallint
  FROM (SELECT DISTINCT jenis_pekerjaan FROM public.bom_proses_relevan
        WHERE tipe_panel = p_tipe_panel AND kode_komponen = p_kode_komponen
          AND jenis_pekerjaan IN ('POTONG','BENDING','STEL','FINISHING','RENDAM','PAINTING')) r
  ORDER BY 2;
$$;

-- 4. Kondisi per tahap (SATU rumus, dipakai RPC & dibaca app lewat view) -----------------------
CREATE OR REPLACE FUNCTION public.produksi_stok_kondisi(p_batch_id bigint)
RETURNS TABLE (batch_id bigint, tahap text, urutan smallint, qty_selesai integer, qty_reject integer, qty_baik integer, tersedia integer)
LANGUAGE plpgsql STABLE AS $$
DECLARE b public.produksi_stok_batch; r record; v_prev_baik integer := NULL; v_reject_sesudah integer; v_hidup integer;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id;
  IF NOT FOUND THEN RETURN; END IF;
  FOR r IN SELECT t.* FROM public.produksi_stok_tahap t WHERE t.batch_id = p_batch_id ORDER BY t.urutan LOOP
    batch_id := p_batch_id; tahap := r.tahap; urutan := r.urutan;
    qty_selesai := r.qty_selesai; qty_reject := r.qty_reject; qty_baik := r.qty_selesai - r.qty_reject;
    IF v_prev_baik IS NULL THEN
      SELECT COALESCE(SUM(t2.qty_reject),0) INTO v_reject_sesudah FROM public.produksi_stok_tahap t2
        WHERE t2.batch_id = p_batch_id AND t2.urutan > r.urutan;
      v_hidup := qty_baik - v_reject_sesudah;
      tersedia := CASE WHEN b.status = 'aktif' THEN GREATEST(0, b.target_qty - v_hidup) ELSE 0 END;
    ELSE
      tersedia := CASE WHEN b.status = 'aktif' THEN GREATEST(0, v_prev_baik - r.qty_selesai) ELSE 0 END;
    END IF;
    v_prev_baik := qty_baik;
    RETURN NEXT;
  END LOOP;
END $$;

CREATE OR REPLACE VIEW public.v_produksi_stok_tahap WITH (security_invoker = true) AS
  SELECT k.* FROM public.produksi_stok_batch b CROSS JOIN LATERAL public.produksi_stok_kondisi(b.id) k;

-- 5. Cek selesai (internal, dipanggil RPC SETELAH baris batch dikunci) --------------------------
CREATE OR REPLACE FUNCTION public.produksi_stok_cek_selesai(p_batch_id bigint, p_oleh text)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; v_baik_akhir integer; v_wip integer; v_trx public.komponen_stok_transaksi;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id;
  IF b.status <> 'aktif' THEN RETURN; END IF;
  SELECT k.qty_baik INTO v_baik_akhir FROM public.produksi_stok_kondisi(p_batch_id) k ORDER BY k.urutan DESC LIMIT 1;
  SELECT COALESCE(SUM(k.tersedia),0) INTO v_wip FROM public.produksi_stok_kondisi(p_batch_id) k WHERE k.urutan > 1;
  IF v_baik_akhir < b.target_qty OR v_wip > 0 THEN RETURN; END IF;
  SELECT * INTO v_trx FROM public.catat_transaksi_stok(b.komponen_id, 'masuk', v_baik_akhir, 'otomatis_produksi',
    'Produksi stok batch #' || b.id || ' selesai', 'produksi_stok_batch:' || b.id, COALESCE(p_oleh, 'SISTEM'), current_date, NULL);
  UPDATE public.produksi_stok_batch SET status = 'selesai', selesai_at = now(), updated_at = now(), stok_transaksi_id = v_trx.id
  WHERE id = p_batch_id;
END $$;

-- Ringkasan batch utk dikembalikan RPC
CREATE OR REPLACE FUNCTION public.produksi_stok_ringkasan(p_batch_id bigint)
RETURNS json LANGUAGE sql STABLE AS $$
  SELECT json_build_object(
    'batch', (SELECT row_to_json(b) FROM public.produksi_stok_batch b WHERE b.id = p_batch_id),
    'tahap', (SELECT json_agg(row_to_json(k) ORDER BY k.urutan) FROM public.produksi_stok_kondisi(p_batch_id) k));
$$;

-- 6. RPC ----------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.buat_batch_produksi_stok(p_komponen_id bigint, p_target_qty integer, p_created_by text)
RETURNS json LANGUAGE plpgsql AS $$
DECLARE k public.komponen_stok; v_id bigint; v_n integer;
BEGIN
  IF p_target_qty IS NULL OR p_target_qty <= 0 THEN RAISE EXCEPTION 'Target qty harus lebih dari 0'; END IF;
  SELECT * INTO k FROM public.komponen_stok WHERE id = p_komponen_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Komponen stok % tidak ditemukan', p_komponen_id; END IF;
  IF k.bom_tipe_panel IS NULL OR k.bom_kode_komponen IS NULL THEN
    RAISE EXCEPTION 'Komponen "%" belum punya komponen BOM acuan - isi dulu di Stok Komponen', k.nama;
  END IF;
  SELECT COUNT(*) INTO v_n FROM public.produksi_stok_tahap_berlaku(k.bom_tipe_panel, k.bom_kode_komponen);
  IF v_n = 0 THEN
    RAISE EXCEPTION 'Komponen BOM acuan % % tidak punya proses POTONG s/d PAINTING di Master Data proses relevan', k.bom_tipe_panel, k.bom_kode_komponen;
  END IF;
  INSERT INTO public.produksi_stok_batch (komponen_id, target_qty, bom_tipe_panel, bom_kode_komponen, created_by)
  VALUES (p_komponen_id, p_target_qty, k.bom_tipe_panel, k.bom_kode_komponen, p_created_by) RETURNING id INTO v_id;
  INSERT INTO public.produksi_stok_tahap (batch_id, tahap, urutan)
  SELECT v_id, t.tahap, t.urutan FROM public.produksi_stok_tahap_berlaku(k.bom_tipe_panel, k.bom_kode_komponen) t;
  RETURN public.produksi_stok_ringkasan(v_id);
END $$;

CREATE OR REPLACE FUNCTION public.simpan_progress_produksi_stok(
  p_batch_id bigint, p_tahap text, p_qty integer, p_qty_reject integer, p_foto_urls text[],
  p_operator_id bigint, p_operator_nama text, p_catatan text DEFAULT NULL, p_mulai_at timestamptz DEFAULT NULL
) RETURNS json LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; v_tersedia integer; v_reject integer := COALESCE(p_qty_reject, 0);
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id FOR UPDATE;  -- serialisasi per batch
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, tidak bisa ditambah progress', b.status; END IF;
  IF p_qty IS NULL OR p_qty <= 0 THEN RAISE EXCEPTION 'Jumlah selesai sesi ini harus lebih dari 0'; END IF;
  IF v_reject < 0 OR v_reject > p_qty THEN RAISE EXCEPTION 'Jumlah reject harus antara 0 dan %', p_qty; END IF;
  IF p_foto_urls IS NULL OR cardinality(p_foto_urls) < 1 THEN RAISE EXCEPTION 'Foto hasil wajib diisi minimal 1'; END IF;
  SELECT k.tersedia INTO v_tersedia FROM public.produksi_stok_kondisi(p_batch_id) k WHERE k.tahap = p_tahap;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tahap % tidak berlaku untuk batch ini', p_tahap; END IF;
  IF p_qty > v_tersedia THEN
    RAISE EXCEPTION 'Jumlah melebihi yang tersedia di tahap % (maksimal % pcs saat ini)', p_tahap, v_tersedia;
  END IF;
  UPDATE public.produksi_stok_tahap
    SET qty_selesai = qty_selesai + p_qty, qty_reject = qty_reject + v_reject, updated_at = now()
  WHERE batch_id = p_batch_id AND tahap = p_tahap;
  INSERT INTO public.produksi_stok_log (batch_id, tahap, qty_sesi_ini, qty_reject_sesi_ini, foto_urls, operator_id, operator_nama, catatan, mulai_at)
  VALUES (p_batch_id, p_tahap, p_qty, v_reject, p_foto_urls, p_operator_id, p_operator_nama, p_catatan, p_mulai_at);
  UPDATE public.produksi_stok_batch SET updated_at = now() WHERE id = p_batch_id;
  PERFORM public.produksi_stok_cek_selesai(p_batch_id, p_operator_nama);
  RETURN public.produksi_stok_ringkasan(p_batch_id);
END $$;

CREATE OR REPLACE FUNCTION public.ubah_target_produksi_stok(p_batch_id bigint, p_target_qty integer, p_oleh text)
RETURNS json LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, target tidak bisa diubah', b.status; END IF;
  IF p_target_qty IS NULL OR p_target_qty <= 0 THEN RAISE EXCEPTION 'Target qty harus lebih dari 0'; END IF;
  UPDATE public.produksi_stok_batch SET target_qty = p_target_qty, updated_at = now() WHERE id = p_batch_id;
  PERFORM public.produksi_stok_cek_selesai(p_batch_id, p_oleh);
  RETURN public.produksi_stok_ringkasan(p_batch_id);
END $$;

CREATE OR REPLACE FUNCTION public.batal_produksi_stok(p_batch_id bigint, p_oleh text, p_alasan text DEFAULT NULL)
RETURNS json LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; v_baik_akhir integer; v_trx public.komponen_stok_transaksi;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, tidak bisa dibatalkan', b.status; END IF;
  SELECT k.qty_baik INTO v_baik_akhir FROM public.produksi_stok_kondisi(p_batch_id) k ORDER BY k.urutan DESC LIMIT 1;
  IF COALESCE(v_baik_akhir, 0) > 0 THEN
    SELECT * INTO v_trx FROM public.catat_transaksi_stok(b.komponen_id, 'masuk', v_baik_akhir, 'otomatis_produksi',
      'Produksi stok batch #' || b.id || ' DIBATALKAN - barang jadi yang sudah ada dimasukkan', 'produksi_stok_batch:' || b.id,
      COALESCE(p_oleh, 'SISTEM'), current_date, NULL);
  END IF;
  UPDATE public.produksi_stok_batch
    SET status = 'batal', updated_at = now(), selesai_at = now(), dibatalkan_oleh = p_oleh, alasan_batal = p_alasan,
        stok_transaksi_id = v_trx.id
  WHERE id = p_batch_id;
  RETURN public.produksi_stok_ringkasan(p_batch_id);
END $$;

GRANT EXECUTE ON FUNCTION public.produksi_stok_tahap_berlaku(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.produksi_stok_kondisi(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.produksi_stok_ringkasan(bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.buat_batch_produksi_stok(bigint, integer, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.simpan_progress_produksi_stok(bigint, text, integer, integer, text[], bigint, text, text, timestamptz) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ubah_target_produksi_stok(bigint, integer, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.batal_produksi_stok(bigint, text, text) TO anon, authenticated;
GRANT SELECT ON public.v_produksi_stok_tahap TO anon, authenticated;

-- 7. Realtime -------------------------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    FOREACH t IN ARRAY ARRAY['produksi_stok_batch','produksi_stok_tahap','produksi_stok_log'] LOOP
      IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t) THEN
        EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
      END IF;
    END LOOP;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
COMMIT;
