-- ============================================================================================
-- PRODUKSI STOK - SESI BERJALAN DI SERVER (2 Okt 2026, permintaan user: panel "Sesi Produksi Stok
-- Aktif" + toast untuk Admin). Sebelumnya waktu "Mulai" cuma disimpan di localStorage HP operator
-- dan produksi_stok_log baru terisi saat Simpan Progress, jadi sesi yang SEDANG berjalan tidak
-- terlihat dari mana pun. Tabel ini = satu-satunya sumber "sesi berjalan".
--
-- Jalankan di SQL Editor SEBELUM push app (vista-pekerja/vista-teknik) yang memanggil RPC baru.
-- App lama tetap jalan: signature simpan_progress_produksi_stok & batal_produksi_stok TIDAK
-- berubah, cuma ditambah langkah menutup sesi terbuka. Aman dijalankan ulang.
-- Tidak menyentuh panels / raw_schedule / renhar / WO / fcs_timer_kerja sama sekali.
-- ============================================================================================
BEGIN;

-- 1. Tabel sesi ------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.produksi_stok_sesi (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id       bigint NOT NULL REFERENCES public.produksi_stok_batch(id) ON DELETE CASCADE,
  tahap          text   NOT NULL,
  operator_id    bigint,
  operator_nama  text   NOT NULL,
  sub_bagian     text,
  mulai_at       timestamptz NOT NULL DEFAULT now(),   -- jam SERVER, bukan jam HP
  selesai_at     timestamptz,                          -- NULL = sesi masih berjalan
  cara_selesai   text CHECK (cara_selesai IN ('stop','simpan','batal','batch_selesai','tutup_admin')),
  ditutup_oleh   text,
  CHECK ((selesai_at IS NULL) = (cara_selesai IS NULL)),
  FOREIGN KEY (batch_id, tahap) REFERENCES public.produksi_stok_tahap(batch_id, tahap) ON DELETE CASCADE
);
-- 1 operator maks 1 sesi terbuka per kartu (batch+tahap). Mulai dobel (tap 2x / 2 HP) = sesi yg sama.
CREATE UNIQUE INDEX IF NOT EXISTS produksi_stok_sesi_terbuka_unik
  ON public.produksi_stok_sesi (batch_id, tahap, lower(operator_nama)) WHERE selesai_at IS NULL;
CREATE INDEX IF NOT EXISTS produksi_stok_sesi_terbuka_idx
  ON public.produksi_stok_sesi (mulai_at) WHERE selesai_at IS NULL;

ALTER TABLE public.produksi_stok_sesi ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS produksi_stok_sesi_anon_all ON public.produksi_stok_sesi;
CREATE POLICY produksi_stok_sesi_anon_all ON public.produksi_stok_sesi FOR ALL USING (true) WITH CHECK (true);

-- 2. Mulai sesi: idempotent - kalau sesi terbuka utk operator+kartu ini sudah ada, itu yg dikembalikan
--    (timer tidak reset). Hanya INSERT sungguhan yang memicu toast Admin (realtime INSERT).
CREATE OR REPLACE FUNCTION public.mulai_sesi_produksi_stok(
  p_batch_id bigint, p_tahap text, p_operator_id bigint, p_operator_nama text, p_sub_bagian text DEFAULT NULL
) RETURNS public.produksi_stok_sesi LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; s public.produksi_stok_sesi;
BEGIN
  IF p_operator_nama IS NULL OR btrim(p_operator_nama) = '' THEN RAISE EXCEPTION 'Nama operator wajib diisi'; END IF;
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, tidak bisa mulai sesi', b.status; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.produksi_stok_tahap WHERE batch_id = p_batch_id AND tahap = p_tahap) THEN
    RAISE EXCEPTION 'Tahap % tidak berlaku untuk batch ini', p_tahap;
  END IF;
  INSERT INTO public.produksi_stok_sesi (batch_id, tahap, operator_id, operator_nama, sub_bagian)
  VALUES (p_batch_id, p_tahap, p_operator_id, p_operator_nama, p_sub_bagian)
  ON CONFLICT (batch_id, tahap, lower(operator_nama)) WHERE selesai_at IS NULL DO NOTHING
  RETURNING * INTO s;
  IF s.id IS NULL THEN
    SELECT * INTO s FROM public.produksi_stok_sesi
    WHERE batch_id = p_batch_id AND tahap = p_tahap AND lower(operator_nama) = lower(p_operator_nama) AND selesai_at IS NULL;
  END IF;
  RETURN s;
END $$;

-- 3. Tutup sesi: Stop operator ('stop') atau koreksi Admin ('tutup_admin'). Sudah tertutup = no-op.
CREATE OR REPLACE FUNCTION public.stop_sesi_produksi_stok(
  p_sesi_id bigint, p_cara text DEFAULT 'stop', p_oleh text DEFAULT NULL
) RETURNS public.produksi_stok_sesi LANGUAGE plpgsql AS $$
DECLARE s public.produksi_stok_sesi;
BEGIN
  IF p_cara NOT IN ('stop','tutup_admin') THEN RAISE EXCEPTION 'Cara tutup sesi tidak dikenal: %', p_cara; END IF;
  UPDATE public.produksi_stok_sesi SET selesai_at = now(), cara_selesai = p_cara, ditutup_oleh = p_oleh
  WHERE id = p_sesi_id AND selesai_at IS NULL
  RETURNING * INTO s;
  IF s.id IS NULL THEN
    SELECT * INTO s FROM public.produksi_stok_sesi WHERE id = p_sesi_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Sesi produksi % tidak ditemukan', p_sesi_id; END IF;
  END IF;
  RETURN s;
END $$;

-- 4. Simpan progress: signature & validasi SAMA dgn 20261002040000. Tambahan:
--    - mulai_at log diisi dari sesi terbuka operator ini kalau app tidak mengirim p_mulai_at;
--    - sesi terbuka operator ini di kartu ini ditutup ('simpan');
--    - kalau batch jadi selesai, semua sesi terbuka batch itu ditutup ('batch_selesai').
CREATE OR REPLACE FUNCTION public.simpan_progress_produksi_stok(
  p_batch_id bigint, p_tahap text, p_qty integer, p_qty_reject integer, p_foto_urls text[],
  p_operator_id bigint, p_operator_nama text, p_catatan text DEFAULT NULL, p_mulai_at timestamptz DEFAULT NULL
) RETURNS json LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; v_tersedia integer; v_reject integer := COALESCE(p_qty_reject, 0);
        v_mulai timestamptz := p_mulai_at; v_status text;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id FOR UPDATE;  -- serialisasi per batch
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, tidak bisa ditambah progress', b.status; END IF;
  IF p_qty IS NULL OR p_qty <= 0 THEN RAISE EXCEPTION 'Jumlah selesai sesi ini harus lebih dari 0'; END IF;
  IF v_reject < 0 OR v_reject > p_qty THEN RAISE EXCEPTION 'Jumlah reject harus antara 0 dan %', p_qty; END IF;
  SELECT k.tersedia INTO v_tersedia FROM public.produksi_stok_kondisi(p_batch_id) k WHERE k.tahap = p_tahap;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tahap % tidak berlaku untuk batch ini', p_tahap; END IF;
  IF p_qty > v_tersedia THEN
    RAISE EXCEPTION 'Jumlah melebihi yang tersedia di tahap % (maksimal % pcs saat ini)', p_tahap, v_tersedia;
  END IF;
  IF v_mulai IS NULL AND p_operator_nama IS NOT NULL THEN
    SELECT s.mulai_at INTO v_mulai FROM public.produksi_stok_sesi s
    WHERE s.batch_id = p_batch_id AND s.tahap = p_tahap AND lower(s.operator_nama) = lower(p_operator_nama) AND s.selesai_at IS NULL;
  END IF;
  UPDATE public.produksi_stok_tahap
    SET qty_selesai = qty_selesai + p_qty, qty_reject = qty_reject + v_reject, updated_at = now()
  WHERE batch_id = p_batch_id AND tahap = p_tahap;
  INSERT INTO public.produksi_stok_log (batch_id, tahap, qty_sesi_ini, qty_reject_sesi_ini, foto_urls, operator_id, operator_nama, catatan, mulai_at)
  VALUES (p_batch_id, p_tahap, p_qty, v_reject, COALESCE(p_foto_urls, '{}'::text[]), p_operator_id, p_operator_nama, p_catatan, v_mulai);
  IF p_operator_nama IS NOT NULL THEN
    UPDATE public.produksi_stok_sesi SET selesai_at = now(), cara_selesai = 'simpan', ditutup_oleh = p_operator_nama
    WHERE batch_id = p_batch_id AND tahap = p_tahap AND lower(operator_nama) = lower(p_operator_nama) AND selesai_at IS NULL;
  END IF;
  UPDATE public.produksi_stok_batch SET updated_at = now() WHERE id = p_batch_id;
  PERFORM public.produksi_stok_cek_selesai(p_batch_id, p_operator_nama);
  SELECT status INTO v_status FROM public.produksi_stok_batch WHERE id = p_batch_id;
  IF v_status <> 'aktif' THEN
    UPDATE public.produksi_stok_sesi SET selesai_at = now(), cara_selesai = 'batch_selesai', ditutup_oleh = 'SISTEM'
    WHERE batch_id = p_batch_id AND selesai_at IS NULL;
  END IF;
  RETURN public.produksi_stok_ringkasan(p_batch_id);
END $$;

-- 5. Batal batch: logika SAMA dgn 20261002030000 + tutup semua sesi terbuka batch itu ('batal').
CREATE OR REPLACE FUNCTION public.batal_produksi_stok(p_batch_id bigint, p_oleh text, p_alasan text DEFAULT NULL)
RETURNS json LANGUAGE plpgsql AS $$
DECLARE b public.produksi_stok_batch; v_baik_akhir integer; v_trx public.komponen_stok_transaksi;
BEGIN
  SELECT * INTO b FROM public.produksi_stok_batch WHERE id = p_batch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Batch produksi % tidak ditemukan', p_batch_id; END IF;
  IF b.status <> 'aktif' THEN RAISE EXCEPTION 'Batch produksi sudah %, tidak bisa dibatalkan', b.status; END IF;
  SELECT k.qty_baik INTO v_baik_akhir FROM public.produksi_stok_kondisi(p_batch_id) k ORDER BY k.urutan DESC LIMIT 1;
  IF COALESCE(v_baik_akhir, 0) > 0 THEN
    SELECT * INTO v_trx FROM public.catat_transaksi_stok(b.komponen_id, 'masuk', v_baik_akhir, 'otomatis_produksi',
      'Produksi stok batch #' || b.id || ' DIBATALKAN - barang jadi yang sudah ada dimasukkan', 'produksi_stok_batch:' || b.id,
      COALESCE(p_oleh, 'SISTEM'), current_date, NULL);
  END IF;
  UPDATE public.produksi_stok_batch
    SET status = 'batal', updated_at = now(), selesai_at = now(), dibatalkan_oleh = p_oleh, alasan_batal = p_alasan,
        stok_transaksi_id = v_trx.id
  WHERE id = p_batch_id;
  UPDATE public.produksi_stok_sesi SET selesai_at = now(), cara_selesai = 'batal', ditutup_oleh = COALESCE(p_oleh, 'SISTEM')
  WHERE batch_id = p_batch_id AND selesai_at IS NULL;
  RETURN public.produksi_stok_ringkasan(p_batch_id);
END $$;

GRANT EXECUTE ON FUNCTION public.mulai_sesi_produksi_stok(bigint, text, bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.stop_sesi_produksi_stok(bigint, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.simpan_progress_produksi_stok(bigint, text, integer, integer, text[], bigint, text, text, timestamptz) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.batal_produksi_stok(bigint, text, text) TO anon, authenticated;

-- 6. Realtime (panel & toast Admin dengar INSERT/UPDATE tabel ini) ---------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'produksi_stok_sesi') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.produksi_stok_sesi;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
COMMIT;
