-- ============================================================================================
-- FONDASI STOK KOMPONEN (2 Okt 2026) - DRAFT, BELUM DIJALANKAN. Jalankan di Supabase SQL Editor
-- (tim ini apply skema manual, file ini dokumentasi + sumber yang di-copy ke SQL Editor).
--
-- Murni TAMBAHAN, gak ada kolom/tabel lama yang dihapus/di-rename:
--   1. komponen_stok + kolom jenis, dimensi (nullable) - kolom `kode` TETAP (alias/kode lama).
--   2. Tabel baru komponen_stok_transaksi - SATU-SATUNYA jalur yang mengubah komponen_stok.stok.
--   3. RPC catat_transaksi_stok() - atomik: kunci baris, cek stok, update stok, insert transaksi
--      dalam 1 transaksi DB (ganti pola fresh-read + conditional update di client).
--   4. Trigger jaring pengaman: perubahan stok yang TIDAK lewat RPC (insert stok awal / update
--      angka langsung dari client manapun) otomatis dicatat - gak ada perubahan diam-diam.
--   5. Backfill jenis/dimensi 21 baris + saldo awal transaksi + migrasi komponen_stok_masuk.
--   6. Cek konsistensi: jumlah transaksi per komponen == stok tersimpan.
-- komponen_stok_masuk TIDAK dihapus (dibiarkan selama transisi, gak ditulis lagi oleh app).
-- Seluruh file dibungkus 1 transaksi: kalau satu langkah gagal (termasuk cek konsistensi),
-- SEMUANYA batal otomatis, database kembali persis seperti sebelum dijalankan.
-- ============================================================================================
BEGIN;

-- 1. Kolom baru --------------------------------------------------------------------------------
ALTER TABLE public.komponen_stok
  ADD COLUMN IF NOT EXISTS jenis   text,
  ADD COLUMN IF NOT EXISTS dimensi text;
COMMENT ON COLUMN public.komponen_stok.jenis   IS 'Jenis komponen stok (mis. UNP, HGR, FR-DPN-SGL-KR). Pengganti terstruktur dari prefix kolom kode.';
COMMENT ON COLUMN public.komponen_stok.dimensi IS 'Dimensi (mis. 700x1400 utk UNP, 1190 utk HGR/FR). Teks, format bebas tapi konsisten per jenis.';
COMMENT ON COLUMN public.komponen_stok.kode    IS 'Kode lama (teks bebas) - DIPERTAHANKAN sbg alias selama transisi ke jenis+dimensi. Bisa berubah (pernah di-edit), jangan dipakai sbg relasi - pakai id.';

-- 2. Tabel transaksi ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.komponen_stok_transaksi (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  komponen_id   bigint NOT NULL REFERENCES public.komponen_stok(id) ON DELETE CASCADE,
  tipe          text   NOT NULL CHECK (tipe IN ('masuk','keluar','koreksi')),
  sumber        text   NOT NULL CHECK (sumber IN ('manual','otomatis_produksi','koreksi_manual')),
  -- masuk/keluar: jumlah positif. koreksi: selisih bertanda (stok_sesudah - stok_sebelum, != 0).
  jumlah        integer NOT NULL,
  stok_sebelum  integer NOT NULL,
  stok_sesudah  integer NOT NULL CHECK (stok_sesudah >= 0),
  tanggal       date   NOT NULL DEFAULT current_date,
  keterangan    text,
  referensi     text,   -- nullable: proyek (keluar manual) / nanti link ke WO atau batch Produksi Stok
  panel         text,   -- nullable: panel tujuan (transaksi keluar manual)
  created_by    text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT komponen_stok_transaksi_jumlah_valid CHECK (
    (tipe IN ('masuk','keluar') AND jumlah > 0) OR (tipe = 'koreksi' AND jumlah <> 0)
  ),
  CONSTRAINT komponen_stok_transaksi_saldo_valid CHECK (
    stok_sesudah = stok_sebelum + CASE WHEN tipe = 'keluar' THEN -jumlah ELSE jumlah END
  )
);
CREATE INDEX IF NOT EXISTS komponen_stok_transaksi_komponen_idx ON public.komponen_stok_transaksi (komponen_id, created_at DESC);
CREATE INDEX IF NOT EXISTS komponen_stok_transaksi_tanggal_idx  ON public.komponen_stok_transaksi (tanggal DESC);
-- RLS: pola sama tabel app lain (component_process_progress dkk) - otentikasi di level app.
ALTER TABLE public.komponen_stok_transaksi ENABLE ROW LEVEL SECURITY;
CREATE POLICY komponen_stok_transaksi_anon_all ON public.komponen_stok_transaksi FOR ALL USING (true) WITH CHECK (true);
-- Realtime: halaman Stok (KomponenStokTab/StokMonitoringTab) dengar INSERT tabel ini. Dijaga
-- biar gak gagal kalau publikasi gak ada / tabel sudah terdaftar.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime')
     AND NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'komponen_stok_transaksi') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.komponen_stok_transaksi;
  END IF;
END $$;
COMMENT ON TABLE public.komponen_stok_transaksi IS
  'Riwayat SEMUA perubahan komponen_stok.stok (masuk/keluar/koreksi). Ditulis lewat RPC catat_transaksi_stok; trigger trg_komponen_stok_catat menangkap perubahan di luar RPC sebagai koreksi.';

-- 3. Backfill (SEBELUM trigger dipasang, biar gak dobel tercatat) --------------------------------
-- 3a. jenis + dimensi 21 baris (nilai hasil preview yang sudah direview, dicocokkan per id+kode
--     biar kalau ada baris yang kodenya berubah sejak preview, baris itu dilewati, bukan salah isi).
UPDATE public.komponen_stok k SET jenis = v.jenis, dimensi = v.dimensi
FROM (VALUES
  (11,'UNP7001400','UNP','700x1400'),   (12,'UNP8001400','UNP','800x1400'),
  (13,'UNP12001200','UNP','1200x1200'), (14,'UNP13001500','UNP','1300x1500'),
  (15,'UNP7001200','UNP','700x1200'),   (16,'UNP7001000','UNP','700x1000'),
  (17,'UNP8001300','UNP','800x1300'),   (18,'UNP10001200','UNP','1000x1200'),
  (19,'UNP800800','UNP','800x800'),     (20,'UNP600800','UNP','600x800'),
  (21,'HGR1400','HGR','1400'), (22,'HGR800','HGR','800'), (23,'HGR1100','HGR','1100'),
  (24,'HGR1190','HGR','1190'), (25,'HGR750','HGR','750'),
  (26,'FR-DPN-DBL-KPTR-1200','FR-DPN-DBL-KPTR','1200'),
  (27,'FR-DPN-DBL-BSRKCL-KR-1000','FR-DPN-DBL-BSRKCL-KR','1000'),
  (28,'FR-DPN-SGL-KR-700','FR-DPN-SGL-KR','700'),
  (29,'FR-BLKG-600','FR-BLKG','600'), (30,'FR-BLKG-800','FR-BLKG','800'),
  (31,'FR-DPN-SGL-KN-1000','FR-DPN-SGL-KN','1000')
) AS v(id, kode, jenis, dimensi)
WHERE k.id = v.id AND k.kode = v.kode AND k.jenis IS NULL;

-- 3b. Saldo awal: stok yang SUDAH ADA sebelum riwayat transaksi ada (diisi lewat edit langsung,
--     gak pernah tercatat). Dikurangi total komponen_stok_masuk (yang dimigrasi terpisah di 3c)
--     biar gak kehitung dobel. Batal total kalau ada saldo awal negatif (data gak konsisten).
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT k.id, k.stok, k.created_at, k.created_by,
           COALESCE((SELECT SUM(m.jumlah) FROM public.komponen_stok_masuk m WHERE m.komponen_id = k.id), 0) AS total_masuk
    FROM public.komponen_stok k
  LOOP
    IF COALESCE(r.stok,0) - r.total_masuk < 0 THEN
      RAISE EXCEPTION 'Saldo awal negatif utk komponen % (stok %, total masuk %) - migrasi dibatalkan', r.id, r.stok, r.total_masuk;
    END IF;
    IF COALESCE(r.stok,0) - r.total_masuk > 0 THEN
      INSERT INTO public.komponen_stok_transaksi (komponen_id, tipe, sumber, jumlah, stok_sebelum, stok_sesudah, tanggal, keterangan, created_by, created_at)
      VALUES (r.id, 'koreksi', 'koreksi_manual', r.stok - r.total_masuk, 0, r.stok - r.total_masuk,
              COALESCE(r.created_at::date, current_date),
              'Saldo awal migrasi - stok sudah ada sebelum riwayat transaksi dicatat', 'MIGRASI', COALESCE(r.created_at, now()));
    END IF;
  END LOOP;
END $$;

-- 3c. komponen_stok_masuk -> transaksi 'masuk' (urut tanggal, saldo berjalan dari saldo awal).
INSERT INTO public.komponen_stok_transaksi (komponen_id, tipe, sumber, jumlah, stok_sebelum, stok_sesudah, tanggal, keterangan, created_by, created_at)
SELECT m.komponen_id, 'masuk', 'manual', m.jumlah,
       (k.stok - SUM(m.jumlah) OVER w_total) + SUM(m.jumlah) OVER w_jalan - m.jumlah,
       (k.stok - SUM(m.jumlah) OVER w_total) + SUM(m.jumlah) OVER w_jalan,
       m.tanggal, m.keterangan, m.created_by, COALESCE(m.created_at, now())
FROM public.komponen_stok_masuk m
JOIN public.komponen_stok k ON k.id = m.komponen_id
WHERE m.jumlah > 0
WINDOW w_total AS (PARTITION BY m.komponen_id),
       w_jalan AS (PARTITION BY m.komponen_id ORDER BY m.tanggal, m.id ROWS UNBOUNDED PRECEDING);

-- 4. RPC atomik ----------------------------------------------------------------------------------
-- p_jumlah: masuk/keluar = jumlah (>0). koreksi = STOK TARGET (angka baru yang diketik user) -
-- selisihnya dihitung di sini. Koreksi tanpa perubahan = no-op (gak bikin baris kosong).
CREATE OR REPLACE FUNCTION public.catat_transaksi_stok(
  p_komponen_id bigint, p_tipe text, p_jumlah integer,
  p_sumber text DEFAULT 'manual', p_keterangan text DEFAULT NULL, p_referensi text DEFAULT NULL,
  p_created_by text DEFAULT NULL, p_tanggal date DEFAULT current_date, p_panel text DEFAULT NULL
) RETURNS public.komponen_stok_transaksi
LANGUAGE plpgsql AS $$
DECLARE v_lama integer; v_baru integer; v_jumlah integer; v_row public.komponen_stok_transaksi;
BEGIN
  SELECT COALESCE(stok,0) INTO v_lama FROM public.komponen_stok WHERE id = p_komponen_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Komponen stok % tidak ditemukan', p_komponen_id; END IF;
  IF p_tipe = 'masuk' THEN
    IF p_jumlah IS NULL OR p_jumlah <= 0 THEN RAISE EXCEPTION 'Jumlah masuk harus lebih dari 0'; END IF;
    v_jumlah := p_jumlah; v_baru := v_lama + p_jumlah;
  ELSIF p_tipe = 'keluar' THEN
    IF p_jumlah IS NULL OR p_jumlah <= 0 THEN RAISE EXCEPTION 'Jumlah keluar harus lebih dari 0'; END IF;
    IF p_jumlah > v_lama THEN RAISE EXCEPTION 'Stok tidak cukup! Stok tersedia: %', v_lama; END IF;
    v_jumlah := p_jumlah; v_baru := v_lama - p_jumlah;
  ELSIF p_tipe = 'koreksi' THEN
    IF p_jumlah IS NULL OR p_jumlah < 0 THEN RAISE EXCEPTION 'Stok koreksi tidak boleh negatif'; END IF;
    IF p_jumlah = v_lama THEN RETURN NULL; END IF;
    v_jumlah := p_jumlah - v_lama; v_baru := p_jumlah;
  ELSE
    RAISE EXCEPTION 'Tipe transaksi tidak dikenal: %', p_tipe;
  END IF;
  -- tandai perubahan ini lewat RPC (dibaca trigger, biar gak dicatat dobel sebagai koreksi)
  PERFORM set_config('app.stok_via_rpc', '1', true);
  UPDATE public.komponen_stok SET stok = v_baru, updated_at = now() WHERE id = p_komponen_id;
  PERFORM set_config('app.stok_via_rpc', '0', true);
  INSERT INTO public.komponen_stok_transaksi (komponen_id, tipe, sumber, jumlah, stok_sebelum, stok_sesudah, tanggal, keterangan, referensi, panel, created_by)
  VALUES (p_komponen_id, p_tipe, COALESCE(p_sumber, CASE WHEN p_tipe='koreksi' THEN 'koreksi_manual' ELSE 'manual' END),
          v_jumlah, v_lama, v_baru, COALESCE(p_tanggal, current_date), p_keterangan, p_referensi, p_panel, p_created_by)
  RETURNING * INTO v_row;
  RETURN v_row;
END $$;
GRANT EXECUTE ON FUNCTION public.catat_transaksi_stok(bigint, text, integer, text, text, text, text, date, text) TO anon, authenticated;

-- 5. Trigger jaring pengaman ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.trg_komponen_stok_catat() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF COALESCE(current_setting('app.stok_via_rpc', true), '0') = '1' THEN RETURN NEW; END IF;
  IF TG_OP = 'INSERT' THEN
    IF COALESCE(NEW.stok,0) > 0 THEN
      INSERT INTO public.komponen_stok_transaksi (komponen_id, tipe, sumber, jumlah, stok_sebelum, stok_sesudah, keterangan, created_by)
      -- 'koreksi' (BUKAN 'masuk'): stok awal dulu gak pernah tampil di riwayat/total masuk - jaga
      -- tampilan tetap sama, & konsisten dgn saldo awal migrasi (juga koreksi).
      VALUES (NEW.id, 'koreksi', 'koreksi_manual', NEW.stok, 0, NEW.stok, 'Stok awal saat komponen ditambahkan', NEW.created_by);
    END IF;
  ELSIF TG_OP = 'UPDATE' AND COALESCE(NEW.stok,0) IS DISTINCT FROM COALESCE(OLD.stok,0) THEN
    INSERT INTO public.komponen_stok_transaksi (komponen_id, tipe, sumber, jumlah, stok_sebelum, stok_sesudah, keterangan, created_by)
    VALUES (NEW.id, 'koreksi', 'koreksi_manual', COALESCE(NEW.stok,0) - COALESCE(OLD.stok,0), COALESCE(OLD.stok,0), COALESCE(NEW.stok,0),
            'Perubahan stok langsung (di luar RPC) - dicatat otomatis', 'edit-langsung');
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_komponen_stok_catat ON public.komponen_stok;
CREATE TRIGGER trg_komponen_stok_catat AFTER INSERT OR UPDATE OF stok ON public.komponen_stok
  FOR EACH ROW EXECUTE FUNCTION public.trg_komponen_stok_catat();

-- 6. Cek konsistensi - BATAL TOTAL kalau ada komponen yang jumlah transaksinya != stok tersimpan.
DO $$
DECLARE n integer;
BEGIN
  SELECT COUNT(*) INTO n FROM public.komponen_stok k
  WHERE COALESCE(k.stok,0) <> COALESCE((
    SELECT SUM(CASE WHEN t.tipe = 'keluar' THEN -t.jumlah ELSE t.jumlah END)
    FROM public.komponen_stok_transaksi t WHERE t.komponen_id = k.id), 0);
  IF n > 0 THEN RAISE EXCEPTION 'Cek konsistensi gagal: % komponen jumlah transaksinya != stok - migrasi dibatalkan', n; END IF;
END $$;

COMMIT;
