-- Fitur baru "Tab Permintaan Barang" (BBMB & BBMU) - sistem request/approve pengeluaran
-- komponen yang SEBELUMNYA gak ada sama sekali di sistem ini. Independen total dari modul
-- lama (komponen_stok/komponen_stok_masuk di System>Stok, dan panels.warehouse_progress) -
-- TIDAK reuse tabel/kode manapun dari situ, TIDAK menyentuhnya sama sekali.
--
-- BBMB (Bantu) - operator pilih komponen dari master komponen_bbmb_master (diisi admin lewat
-- upload Excel/CSV). BBMU (Utama) - komponen auto-muncul dari BOM riil panel yang dipilih
-- (bom_master/panels.checklist), gak ada master terpisah.
--
-- Header (permintaan) SENGAJA nyimpen snapshot teks (wo_number/proyek/panel_nama) di samping
-- FK wo_id/panel_id - pola yang sama dipakai panel_seksi_archived, biar list gak rusak/perlu
-- join kalau WO/panel itu belakangan diarsipkan.

CREATE TABLE IF NOT EXISTS "public"."komponen_bbmb_master" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" text NOT NULL UNIQUE,
  "satuan" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."permintaan" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jenis" text NOT NULL CHECK ("jenis" IN ('BBMB','BBMU')),
  "operator_nama" text NOT NULL,
  "divisi" text NOT NULL,
  "sub_bagian" text,
  "wo_id" bigint REFERENCES "public"."work_orders"("id"),
  "panel_id" bigint REFERENCES "public"."panels"("id"),
  "wo_number" text,
  "proyek" text,
  "panel_nama" text,
  "created_at" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."permintaan_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "permintaan_id" bigint NOT NULL REFERENCES "public"."permintaan"("id") ON DELETE CASCADE,
  "komponen_bbmb_master_id" bigint REFERENCES "public"."komponen_bbmb_master"("id") ON DELETE SET NULL,
  "kode_komponen" text,
  "nama_komponen" text NOT NULL,
  "qty" numeric NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'pending',
  "catatan_reject" text,
  "updated_by" text,
  "updated_at" timestamptz
);

CREATE INDEX IF NOT EXISTS "idx_permintaan_item_permintaan_id" ON "public"."permintaan_item"("permintaan_id");
CREATE INDEX IF NOT EXISTS "idx_permintaan_divisi" ON "public"."permintaan"("divisi");
CREATE INDEX IF NOT EXISTS "idx_permintaan_jenis" ON "public"."permintaan"("jenis");
CREATE INDEX IF NOT EXISTS "idx_permintaan_created_at" ON "public"."permintaan"("created_at");

-- Sama seperti tabel lain di project ini - gak ada RLS restriktif, akses lewat anon key
-- (PostgREST) sepenuhnya diatur lewat GRANT biasa, bukan policy.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."komponen_bbmb_master" TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."permintaan" TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."permintaan_item" TO anon, authenticated;
